name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: npm install, build, test
              run: |
                npm ci
                npm run build
                npm run test
            - name: Upload artifact
              if: ${{ success() }}
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: |
                    build
                    package.json
                    package-lock.json
    # TODO: Add deploy step